// `npm run bundle:scene`: src/scene-ops.js and everything it imports as one
// ES module, for studio-api to vendor (Art-Talk-Back D-070). Pure code only:
// no DOM, no storage, nothing from the browser.
import { defineConfig } from "vite";

const BANNER =
  "// Generated by booth-studio `npm run bundle:scene` from src/scene-ops.js (Art-Talk-Back D-070).\n" +
  "// Do not edit: change the app and rebuild. CI in both repos fails when a copy is out of date.\n";

export default defineConfig({
  publicDir: false,
  // After Vite's own chunk transforms, which drop leading comments.
  plugins: [{
    name: "banner",
    generateBundle(_options, bundle) {
      for (const chunk of Object.values(bundle)) if (chunk.type === "chunk") chunk.code = BANNER + chunk.code;
    },
  }],
  build: {
    outDir: "dist-scene",
    emptyOutDir: true,
    minify: false,
    target: "es2022",
    lib: { entry: "src/scene-ops.js", formats: ["es"], fileName: () => "booth-scene.js" },
  },
});
