// Covers the HDRI backdrop path with assets actually present, which the
// asset-free run in view-lighting.mjs cannot reach: PMREM lighting from a real
// .hdr, an equirectangular backdrop, the headroom from meta.json coming back
// through backgroundIntensity, and the rotation control turning it.
//
// The fixtures are generated by tools/hdri-prep.mjs itself and served from a
// temporary public directory, so the repository's own public/assets is neither
// read nor written and the test behaves the same whether or not the user has
// committed real HDRIs.
import { chromium } from '@playwright/test';
import { createServer } from 'vite';
import { cp, mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { encodeBackdrop, encodeRadiance, headroom } from '../tools/hdri-prep.mjs';

// Four bright quadrants around the horizon: whatever the camera faces, the
// backdrop is visible, and rotating it moves a different colour into view.
function quadrants(width, height) {
  const data = new Float32Array(width * height * 4);
  const colours = [[3, 0.2, 0.2], [0.2, 3, 0.2], [0.2, 0.2, 3], [2.5, 2.5, 0.4]];
  for (let y = 0; y < height; y++)
    for (let x = 0; x < width; x++) {
      const [r, g, b] = colours[Math.floor((x / width) * 4)];
      const sky = y < height / 2 ? 1 : 0.35;
      const o = (y * width + x) * 4;
      data[o] = r * sky; data[o + 1] = g * sky; data[o + 2] = b * sky; data[o + 3] = 1;
    }
  return { width, height, data };
}

const root = new URL('..', import.meta.url).pathname;
const publicDir = await mkdtemp(join(tmpdir(), 'booth-public-'));
const presetDir = join(publicDir, 'assets', 'hdri', 'tradeshow');
const image = quadrants(256, 128);
const intensity = headroom(image);
await cp(join(root, 'public'), publicDir, { recursive: true });
await mkdir(presetDir, { recursive: true });
await writeFile(join(presetDir, 'light.hdr'), encodeRadiance(image));
await writeFile(join(presetDir, 'bg.jpg'), encodeBackdrop(image, { headroom: intensity }));
await writeFile(join(presetDir, 'meta.json'), JSON.stringify({ backgroundIntensity: intensity, credit: 'synthetic fixture' }));

const server = await createServer({ root, publicDir, server: { host: '127.0.0.1', port: 5191 } });
await server.listen();
const browser = await chromium.launch({
  headless: true,
  ...(process.env.BOOTH_TEST_CHROMIUM ? { executablePath: process.env.BOOTH_TEST_CHROMIUM } : {}),
  args: ['--no-sandbox', '--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--use-gl=angle', '--in-process-gpu', '--single-process', '--disable-dev-shm-usage'],
});
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [], warnings = [];
  page.on('pageerror', (e) => errors.push(e.stack || e.message));
  page.on('console', (m) => { if (m.type() === 'warning' || m.type() === 'error') warnings.push(m.text()); });
  await page.goto('http://127.0.0.1:5191');
  await page.waitForFunction(() => !!window.__booth?.scene);

  // The asset files have to be reachable at the paths the presets name, or
  // every assertion below would pass on the procedural fallback instead.
  assert.equal((await page.request.head('http://127.0.0.1:5191/assets/hdri/tradeshow/light.hdr')).status(), 200);

  await page.click('[data-tab="layout"]');
  await page.selectOption('select[aria-label="Environment"]', 'tradeshow');
  await page.waitForFunction(() => !!window.__booth.scene.scene.environment, null, { timeout: 15000 });

  const applied = await page.evaluate(() => {
    const s = window.__booth.scene.scene;
    return {
      environment: !!s.environment?.isTexture,
      background: !!s.background?.isTexture,
      mapping: s.background?.mapping,
      equirect: s.background?.mapping === 303, // EquirectangularReflectionMapping
      colorSpace: s.background?.colorSpace,
      intensity: s.backgroundIntensity,
      fog: s.fog,
      exposure: window.__booth.scene.renderer.toneMappingExposure,
    };
  });
  assert.equal(applied.environment, true, 'the .hdr reached scene.environment through PMREM');
  assert.equal(applied.background, true, 'the .jpg reached scene.background');
  assert.equal(applied.equirect, true, `backdrop mapping ${applied.mapping} is not equirectangular`);
  assert.equal(applied.colorSpace, 'srgb', 'the backdrop is decoded as sRGB');
  assert.equal(applied.fog, null, 'procedural fog would sit in front of a photographed backdrop');
  assert.equal(applied.intensity, intensity, 'meta.json headroom is multiplied back in');
  assert.equal(applied.exposure, 1, 'the trade show preset sets its own exposure');

  // Rotation: the same control a user panorama uses now turns a preset backdrop.
  const rotation = page.locator('input[aria-label="Backdrop rotation"]');
  assert.equal(await rotation.count(), 1, 'a preset with a backdrop offers rotation');
  await rotation.fill('90');
  await rotation.dispatchEvent('change');
  await page.waitForFunction(() => Math.abs(window.__booth.scene.scene.backgroundRotation.y - Math.PI / 2) < 1e-6, null, { timeout: 5000 });
  const turned = await page.evaluate(() => {
    const s = window.__booth.scene.scene;
    return { y: s.backgroundRotation.y, background: !!s.background?.isTexture, intensity: s.backgroundIntensity };
  });
  assert.ok(Math.abs(turned.y - Math.PI / 2) < 1e-6, 'the backdrop turned with the control');
  assert.equal(turned.background, true, 'the backdrop survived the re-render');
  assert.equal(turned.intensity, intensity, 'headroom survived the re-render');

  // Image-based lighting must not reach uploaded artwork on the default setting.
  const shielded = await page.evaluate(() =>
    [...window.__booth.scene.artGroups.values()].map((g) => g.plane.material.envMapIntensity));
  assert.ok(shielded.every((v) => v === 0), 'accurate colour still shields artwork from the HDRI');

  // Going back to a preset with no assets has to release the backdrop.
  await page.selectOption('select[aria-label="Environment"]', 'studio');
  await page.waitForFunction(() => !window.__booth.scene.scene.environment, null, { timeout: 5000 });
  const cleared = await page.evaluate(() => {
    const s = window.__booth.scene.scene;
    return { environment: s.environment, intensity: s.backgroundIntensity, rotation: s.backgroundRotation.y };
  });
  assert.equal(cleared.environment, null, 'the environment map is dropped with the preset');
  assert.equal(cleared.intensity, 1, 'headroom does not leak onto the procedural sky');
  assert.equal(cleared.rotation, 0, 'rotation does not leak onto the procedural sky');

  assert.deepEqual(errors, [], 'no page errors');
  const deprecated = warnings.filter((w) => /deprecated/i.test(w));
  assert.deepEqual(deprecated, [], 'no deprecated three.js loaders');
  console.log('PASS HDRI lighting, backdrop, headroom and rotation with real assets.');
} finally {
  await browser.close();
  await server.close();
  await rm(publicDir, { recursive: true, force: true });
}
